name: CI

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build
        run: |
          chmod +x gradlew
          export TAG="$(echo $GITHUB_REF | grep -q refs/tags && echo ${GITHUB_REF/refs\/tags\/} || echo '')"
          ./gradlew ci
      - name: Docker push
        if: github.event_name == 'push' || startsWith(github.ref, 'refs/tags/')
        run: |
          docker push -a natanbc/andesite
      - name: API javadoc
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: api-docs
          FOLDER: api/build/docs/javadoc
          CLEAN: true
          SINGLE_COMMIT: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/libs/*-all.jar
            jattach-debug-plugin/build/libs/*.jar
            api/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
